apiVersion: gcp.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: default
spec:
  projectID: ${GCP_PROJECT_ID}
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: gcp-provider-creds
      key: credentials
